### ISSUE TITLE
Full CRUD ?

### ISSUE THREAD

**Issue by Mathieu-S** [Mathieu-S/Projet-Annuel#2]
@sokstephane J'ai vu que tu avais ajouter la possibilité de créer un hôtel dans le backoffice mais n'est-il pas plus logique que du coté admin, nous n'ayant qu'à valider, éditer, supprimer les hôtel ?

**Comment by sokstephane** [comment]
Yes je le retirerai du coup

2018-04-13 9:52 GMT+02:00 Mathieu-S <notifications@github.com>:

**Comment by Mathieu-S** [comment]
Tu n'est pas obligé de le supprimer c'est juste que je m'interrogeais.

Je ne sais pas ce que tu en pense mais nous devrions plus utilisé les outils de github

**Comment by sokstephane** [comment]
Les outils de github à quel sujet ? En soit c'est vrai que c'est logique,
enfin l'admin aura pas besoin de faire ça normalement, à moins qu'il y ait
un admin hotelier

**Comment by Mathieu-S** [comment]
Je parle des issues, de l'onglet projet, etc... Pull request on n'en a pas vraiment besoin vu que tu es considérer comme un collaborateur. ça nous permettrais de garder une trace des question que l'on s'est posé et quel problème on a rencontré.

**Comment by sokstephane** [comment]
Okok, je t'avoue que j'connais pas du tout ces outils là mais si c'est cool
yes why not !

**Comment by Mathieu-S** [comment]
Ok ça marche
