### ISSUE TITLE
Classe/Table Option devient un mot clé dans l'ORM

### ISSUE THREAD

**Issue by Mathieu-S** [Mathieu-S/Projet-Annuel#3]
J'ai trouver un gros bug avec l'ORM (Doctrine). La table option deviens un mot clé dans SQL. C'est plus la faute à l'ORM car il ne met pas les cotes dans la requête.

J'ai donc fait un fix rapide sur ma branche, mais je ne sais pas si elle va avoir plus d'incidence à l'avenir.

Pour le moment, la correction oblige à drop la BDD. Il faudra refaire une migration propre et supprimer les anciennes.

**Comment by sokstephane** [comment]
On peut juste renommer la table en par exemple extension du coup non ?

2018-05-01 22:34 GMT+02:00 Mathieu-S <notifications@github.com>:

**Comment by Mathieu-S** [comment]
Malheureusement ça ne suffit pas. J'ai renommé la classe et son repository pour cela fonctionne. Par contre, il est inutile de renommer les attributs dans les entités.

**Comment by sokstephane** [comment]
Ca ne suffit pas pour quelles raisons de renommer la classe et le
repository en question ? Oui les attributs c'est normal qu'ils n'aient pas
à être modifiés en même temps

**Comment by Mathieu-S** [comment]
Les renommer corrige le bug mais la migration est bloquante. C'est pour ça qu'il faut toutes les enlever et en refaire une propre.

On vois ça demains si tu veut.

**Comment by sokstephane** [comment]
Ah d'acc, pas de soucis
