### ISSUE TITLE
Structure du BO

### ISSUE THREAD

**Issue by sokstephane** [Mathieu-S/Projet-Annuel#5]
Hello, 

En mergeant ma branche sur la develop j'ai vu que t'avais fait un tout nouveau dossier de controller pour l'hotelier mais que les controllers étaient identiques à ceux de l'admin, du coup ça fait pas mal de duplicata pour la même chose (notamment l'HotelController qui est similaire dans les 2 cas), ce serait pas mieux de passer le type d'utilisateur en paramètre de la route ( donc au niveau de "/hotelier" ou "/admin") ?

Ca peut peut-être être chiant de tout refaire après et on manquerait peut-être de temps, mais j'voulais savoir si c'était un truc que tu faisais temporairement pour que chacun bosse sur son dossier et ainsi éviter les conflits ou si c'est la solution sur laquelle on part ?

Du coup idem pour les vues, y'en a qui sont dupliquées, pour ça c'est rapide à modifier, ça te va si j'delete genre les vues hotels de l'hotelier pour appeler celles de l'admin (actuellement) mais que j'veux mettre dans le dossier common pour pas qu'on puisse croire que c'est des pages spécifiques à l'admin

**Comment by Mathieu-S** [comment]
Hello

Concernant les duplicata dans les controllers on peut résoudre ce problème par un héritage de droit mais comme tu l'as dis, on a pas vraiment le temps de s'occupé de se genre de détails.

Concernant les vues on pourrait aussi les réorganisé mais encore une fois manque de temps.
