### ISSUE TITLE
Accès aux chambres d'un hôtel en particulier à partir de la page des hôtels

### ISSUE THREAD

**Issue by sokstephane** [Mathieu-S/Projet-Annuel#6]
Hello,

J'ai constaté que t'avais mis le nom de l'hôtel en clickable, redirigeant vers les chambres de l'hôtel en question, je te propose de mettre en bouton l'accès aux chambres sur la ligne concernée et le clic sur le nom de l'hôtel permettra de modifier l'hôtel, enfin c'est une proposition (que j'applique sur ma branche pour le moment en tout cas), ça me parait + intuitif et ergonomique

Screen : http://puu.sh/Ar5xt/fe4886cb7a.jpg

**Comment by Mathieu-S** [comment]
Hello,

Je te laisse le soin d'apporter cette modification. Si tu vois d'autre
détail dans ce genre, tu peux les corrigé directement. L’ergonomie et moi
ça fait 2 XD
Plus sérieusement, je pense terminer les filtre en vueJS cette semaines.
Après il ne "restera" plus que le style et le contenu.

**Comment by sokstephane** [comment]
Okok pas de soucis xD
Cool !
