### ISSUE TITLE
Accessibilité des routes Hotelier

### ISSUE THREAD

**Issue by sokstephane** [Mathieu-S/Projet-Annuel#7]
Hello !

Il ne vaudrait pas mieux laisser également les administrateurs avoir accès aux routes d'hotelier ? De telle sorte à ce qu'ils puissent aussi voir les chambres ou alors tu préfères qu'on laisse ça exclusivement aux hôteliers ? (Je vois l'admin vraiment comme un surhomme qui peut tout faire, mais on peut laisser comme ça aussi, je veux juste confirmer)

**Comment by Mathieu-S** [comment]
Je suis d'accord sur le fait que l'admin est un surhomme et qu'il devrait tout voir. Il faut voir en combien de temps on peut faire la modif.

Si c'est trop long laisse tomber.
